branches:
  only:
    - master
version: '1.1.{build}'
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: fKaSS6YrHCgMckGG62aj1A4WnXYeUnps/SQe8RXpK//ZDl8bCtH3O37Ar/TxMvs0
before_build:
  - nuget restore ".\PublicHolidays.sln"
build:
  project: .\PublicHolidays.sln
  verbosity: minimal
  publish_nuget: true
test:
  assemblies:
    - PublicHolidays.Au.UnitTests
after_test:
  - ps: .\coveralls.ps1
deploy:
  provider: NuGet
  api_key:
    secure: 3BAqdhpg8aurOgSzzMjyo5zV91VRrtzAAgY4Uimp2G+L0NaBlPNFPsUcdsKTF0bx
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
notifications:
  - provider: Email
    to:
      - devadmin@certegy.com.au
      - ryan.bartsch@certegy.com.au
  - provider: Slack
    auth_token:
      secure: QWE2vFI2LUFAu+jx4lXHihtpPFoVi+ru0mHSC/BvsyXYcRvgh7Tc8zEEaKkj1n5V09+Ti39CvVooS3Y8VTn7PYC6lef2OrQQ+ivqkJL+lZI=
    channel: '#alerts'